# **Projeto de Credit Score - Naive Bayes**


Os dados usados foram tratados posteriormente - balanceamento de classes, transformação de variáveis categóricas e separação de base de treino e teste.
Nessa aula aplicaremos o algoritmo de naive bayes a base de vocês afim de tentarmos trazer previsões do score de crédito.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

O Naive Bayes é um algoritmo de classificação probabilístico que calcula a probabilidade de uma amostra pertencer a cada classe e seleciona a classe com a maior probabilidade como a previsão final.

Essa base de dados contém múltiplas variáveis para serem previstas. O Naive Bayes pode ser aplicado para problemas de classificação com múltiplas classes da mesma forma que para problemas de classificação binária.

### 1) Carregar e verificar as bases de treino (X e y) e teste (X e y).

#### Carregando as bases de treino e teste.

In [3]:
X_test = pd.read_csv("X_test.csv", delimiter=',')
X_train = pd.read_csv("X_train_balanced.csv", delimiter=',')
y_test = pd.read_csv("y_test.csv", delimiter=',')
y_train = pd.read_csv("y_train_balanced.csv", delimiter=',')

#### Verificação das bases
Apesar de cada base estar separada em X (variáveis explicativas) e y (variáveis rótulos/a serem previstas), elas devem ter o mesmo tamanho pois, para cada conjunto (linha) de X é preciso ter um rótulo y associado.
Além disso, as bases de X não devem conter a variável rótulo/a ser previsa.

In [14]:
print( "X teste reprovado" if 'Credit Score' in X_test.columns else "X teste não contém a variável rótulo.")

X teste não contém a variável rótulo.


In [16]:
print( "X treino reprovado" if 'Credit Score' in X_train.columns else "X treino não contém a variável rótulo.")

X treino não contém a variável rótulo.


In [17]:
print("X e y teste possuem o mesmo tamanho." if len(y_test)==len(X_test) else "X e y reprovados.")

X e y teste possuem o mesmo tamanho.


In [18]:
print("X e y treino possuem o mesmo tamanho." if len(y_train)==len(X_train) else "X e y reprovados.")

X e y treino possuem o mesmo tamanho.


#### Verificar o balanceamento das variáveis rótulosy da base de treino.
É preciso que o modelo seja treinado com uma base que contenha o mesmo número de dados de cada opção de variável a ser prevista. Caso contrário, haverá, especialmente para o modelo naive, um desequilíbrio no cálculo da probabilidade de ocorrência de cada y. Isso ocorre por que, resumidamente, se uma das opções for mais numerosa que outra, ela se torna mais frequente e, logo, mais provável que ela ocorra.

In [50]:
train_balance = y_train.value_counts()
n0=train_balance[0]

for n in train_balance.items():
    #print(n0,n[1])
    #print(n0==n[1]) 
    print( "Balanceado" if n0==n[1] else "Desbalanceado")
    n0=n[1]

Balanceado
Balanceado
Balanceado


/tmp/ipykernel_38797/2871665982.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  n0=train_balance[0]


### 2) Aplicação do algoritmo de Naive Bayes aos dados de treinamento.

In [53]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

Isso permite que uma instância do classificador Naive Bayes Gaussiano seja criada e o utilizada para realizar tarefas de classificação com base na distribuição gaussiana dos dados.

In [54]:
# Criação de uma instância do classificador Naive Bayes Gaussiano
naive = GaussianNB()
# Treinamento do classificador usando os dados de treinamento
naive.fit(X_train, y_train)

/home/mari/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

### 3) Avaliação do modelo com os dados de treinamento.

Dica: Para calcularmos o recall em classificação multi classe precisamos usar o atributo macro:
recall = recall_score(y_train, y_pred_train, average='macro')

#### Cálculo da Acurácia e Recall e a Matriz Confusão
Para calcular a acurácia, também conhecida como exatidão, são usados os dados de traino. A estratégia é prever os rótulos da base de treino e comparar os valores previstos com os valores conhecidos dessa base de dados
O Recall é o resultado do cálculo que mede a capacidade do modelo em encontrar todos os exemplos positivos.

In [61]:
# Fazer previsões para os dados de treino
y_pred_train = naive.predict(X_train)

accuracy = accuracy_score(y_train, y_pred_train)
recall = recall_score(y_train, y_pred_train, average='macro')

print("Acurácia:", accuracy, "\nRecall:", recall)

Acurácia: 0.996031746031746 
Recall: 0.996031746031746


In [64]:
conf_matrix = confusion_matrix(y_train, y_pred_train)
print(conf_matrix)

[[84  0  0]
 [ 1 83  0]
 [ 0  0 84]]


A matriz confiança indica que houve apenas um erro, uma informação falsa, um falso positivo.
O resultado está em acordo com os altos valores de acurácia e recall.

### 4) Avaliação do modelo com os dados de teste e comparação entre os desempenhos das bases

In [69]:
# Fazer previsões para os dados de teste
y_pred_test = naive.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_test)
recall = recall_score(y_test, y_pred_test, average='macro')

print("Acurácia:", accuracy, "\nRecall:", recall)

Acurácia: 1.0 
Recall: 1.0


In [70]:
conf_matrix = confusion_matrix(y_test, y_pred_test)
print(conf_matrix)

[[ 6  0  0]
 [ 0 29  0]
 [ 0  0  6]]


A matriz confiança indica que o modelo não fez previsões erradas.
O resultado está em acordo com os altos valores de acurácia e recall.

#### Comparação entre os resultados com a base de teste e de treino

Os resultados das bases treino e teste foram similares, ambos tendendo a 1.0. 
Esse resultado indica que o modelo está prevendo os valores muito bem.
Importante destacar que, apesar disso, o modelo não é perfeito, pois ele é um modelo probabilístico: é esperado que ele cometa eventuais erros.
Esta base de dados de teste equivale a aproximadamente 16% da base de treino. Em outras palavras, o número de casos avaliados pelo modelo é muito menor, fazendo com que as chances de erro também sejam menores. Uma base de treino maior poderia ocasionar mais erros.

##### Por que encontrar erros é importante?

Ainda que a acurácia seja 1, o modelo é probabilístico, ele tem chances de acertar e errar. Para ser possível identificar as possíveis fontes de erro, é preciso que o erro ocorra. 
Por isso, no caso de modelos com alta acurácia, é preciso fornecer bases de dados de teste grandes. 

### 5) Discussão

Essa atividade consistiu em treinar um modelo de previsão utilizando o método de aprendizagem supervisionada de classificação com o modelo probabilístico Naive Bayes, também conhecida como Aprendizagem Baysiana. 
O objetivo era a criação de um modelo para previsão do risco de inadimplência - baixa, média e alta - dos cliente de um banco. A previsão é baseada na análise dos dados explicativos (X, features, características).

O modelo foi criado por meio da aprendizagem supervisionada, ou seja, um banco de dados com as informações relevantes sobre diversos clientes e suas pontuações de crédito foi inicialmente dividida entre base de treino e base de teste. A base de treino é a base usada para "ensinar" a máquina, enquanto a base de teste é usada para avaliar a qualidade do modelo resultante dessa aprendizagem. Cada uma dessas bases é dividida em duas partes. A primeira contém os variáveis explicativos, aqueles que possuem as características, features, dos clientes, convencionalmente chamada de X. Já a segunda base é composta pelas variáveis alvo, ou rótulo, aquelas que serão previstas pelo modelo, convencionalmente chamada de y.

O nome desse método, aprendizagem supervisionada, é uma pista de como essas bases serão usadas. Primeiro, um modelo probabilístico é escolhido - nesse caso o modelo Naive Bayes. Esse modelo é então aplicado as bases de treino, tendo como resultado um modelo preditivo. É dito que essa aprendizagem é supervisionada porque o modelo preditivo é criado "sabendo" a resposta certa para cada análise. Ele recebe os dados de entrada (x) e de saída (y) e aprende qual a relação, quais as combinações, entre as variáveis de x costuma gerar cada valor possível de y.

Após essa etapa, os dados de teste foram usados para a análise da qualidade do modelo preditivo. Ele recebeu a base de treino de características (X) e retornou um conjunto de variáveis alvo (y). O conjunto previsto foi então comparado com o conjunto "certo", o conjunto com informações reais. A relação entre esses dois resultados indica o poder de previsão correta do modelo gerado. Quanto mais parecidas forem as bases, maior foi a capacidade de previsão do modelo.

Para avaliar sua qualidade foram analisados três informações: acurácia, recall e matriz confusão. A acurácia mede a capacidade de um modelo probabilístico prever corretamente determinado comportamento, informação. Já o recall e a matriz confusão indicam se "onde" o modelo mais acerta ou erra, se ele retorna mais falsos positivos ou falsos negativos. 

O modelo probabilístico é a máquina que recebe dados e devolve um modelo de previsão. Para a atual aplicação, por se tratarem de dados categóricos, não numéricos, optou-se pela aplicação do modelo de classificação chamado Naive Bayes. Esse modelo parte da premissa de que as variáveis explicativas (X) são independentes entre si, ou seja, o valor de uma não influência na outra. Essa hipótese é considerada simples e dificulta a melhoria do modelo por meio da diversificação do banco de dados. O modelo é eficiente e alcança bons níveis de predição, mas é considerado simples e já foi superado por modelos mais complexos. Atualmente, é muito usado em contextos didáticos como esse, como introdução a modelos classificatórios. 

Por fim, é possível resumir esse processo da seguinte maneira:
A aprendizagem de máquina pode ser entendida como o processo de criação de um modelo preditivo. No caso da aprendizagem supervisionada, essa criação ocorre a partir da análise das relações dos pares entrada-saída. A forma como essa análise é feita depende do modelo probabilístico, e do tipo de dado (categórico ou numérico), avaliado.